services:
  web:
    build: .
    volumes:
      - ./build/libs/fat.jar:/app/ktor-docker-sample.jar
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./tmp/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ktorjournal
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s